### ISSUE TITLE
watch b.c不生效

### ISSUE THREAD

**Issue by janceChun** [HcySunYang/observer-dep-watch#3]
![image](https://user-images.githubusercontent.com/4457572/38547774-8ffff0c6-3ce2-11e8-970f-c2024bf31c45.png)
![image](https://user-images.githubusercontent.com/4457572/38547780-98683bf6-3ce2-11e8-9aee-0160a915ffe9.png)

**Comment by HcySunYang** [comment]
这只是一个博客文章附带的代码，文章的目的是把思路讲清除，代码作为演示，这些代码实际上距离完美还有十万八千里。
